### ISSUE TITLE
Week 9 Functions Assignment Ready for Grading

### ISSUE THREAD

**Issue by shosking-matc** [madisoncollege-it-programs/python-scripting-shosking-matc#13]

**Comment by cethenmc** [comment]
Hi, Spencer.  Fairly nice job.  However, running ./f2c.py should return 0.0.  It does not return anything.  Do you understand why not?  Try to add the if __name__ logic so that if you run the f2c script itself, it runs the main program.  The unchecked boxes were not completed successfully.  I am giving a 6 of 8 for now, but you can resubmit the corrections for full credit.

 
![image](https://user-images.githubusercontent.com/112707666/201392767-9916a1ef-e21b-46c3-bdec-8a740373edd6.png)


![image](https://user-images.githubusercontent.com/112707666/201392614-962b3dbb-3448-4781-85c8-38f75a9e02bb.png)

**Comment by cethenmc** [comment]
Hi, Spencer.  Will you keep the 6 out of 8 on this one?  Or do you plan to submit the correction?

**Comment by cethenmc** [comment]
![image](https://user-images.githubusercontent.com/112707666/207975503-3d3188a9-dea3-4ef4-b407-77c1cc316f10.png)
