### ISSUE TITLE
Week 6 Flow Control Lab Ready for Grading

### ISSUE THREAD

**Issue by shosking-matc** [madisoncollege-it-programs/python-scripting-shosking-matc#8]

**Comment by cethenmc** [comment]
You fulfilled the requirement, but is when choosing door three, and then choosing 2, the response could be improved.  7 of 8 for now,

**Comment by cethenmc** [comment]
Hi Spencer.  I announced in class last week, but I don't think you were present.  I want to close out weeks 1-8 in the grade book.  Do you want me to lock in this 7 of 8, or would you like to correct?  I gave through Sunday 11/6, but I can give you until this Sunday since you were out if you'd like.  Please respond to this issue ticket with your intention.

**Comment by shosking-matc** [comment]
I'm fine with the 7 out of 8 on this assignment.

**Comment by cethenmc** [comment]
Thanks for getting back to me!
