### ISSUE TITLE
Week 7 Dictionaries Assignment is Ready for Grading

### ISSUE THREAD

**Issue by shosking-matc** [madisoncollege-it-programs/python-scripting-shosking-matc#9]

**Comment by cethenmc** [comment]
Hi, Spencer.  # 5 on this assignment was intended to have you add two more records to an already established dictionary (which you established in # 1).  As a result, I will record a 7 of 8, until you send the correction in.  Please reply to this GitHub Issue Ticket to let me know when you have pushed your change to GitHub.  If you just want to take the 7 out of 8, then please reply to this Issue ticket, as well, letting me know.  ~Chris

**Comment by cethenmc** [comment]
Hi Spencer.  I announced in class last week, but I don't think you were present.  I want to close out weeks 1-8 in the grade book.  Do you want me to lock in this 7 of 8, or would you like to correct?  I gave through Sunday 11/6, but I can give you until this Sunday since you were out if you'd like.  Please respond to this issue ticket with your intention.

**Comment by shosking-matc** [comment]
I'm fine with the 7 out of 8 on this assignment.

**Comment by cethenmc** [comment]
Thanks for getting back to me!
